### ISSUE TITLE
GPU out of memory when loading relation embedding

### ISSUE THREAD

**Issue by Jasonqte** [bys0318/QTO#1]
Nice work! However, I found that the relation embedding file in neural_adj folder is too big to load. Even for FB15K-237, the file size is over 50GB. The GPU memory is always out of memory for subsequent processing. Is there any way to optimize it? Thanks

my command: CUDA_VISIBLE_DEVICES=0 python main.py --data_path data/FB15k-237-betae --kbc_path kbc/FB15K-237/best_valid.model --fraction 10 --thrshd 0.0002 --neg_scale 3
my device: Nvidia V100

**Comment by bys0318** [comment]
Thanks for following our work! You can set a higher threshold (--thrshd) to reduce the neural_adj file size, yet with a slight negative effect on the performance. During loading the neural adjacency matrix to GPU, we find it effective to increase --fraction to avoid GPU out-of-memory.

**Comment by bys0318** [comment]
Let me know if you have any other questions! 😊

**Comment by Jasonqte** [comment]
It worked, thank you for your reply! 

1. Another question, I want to run this model on my own dataset, but the query logic of my downstream tasks mainly focus on is 1p, 2p, 3p, 4p, 5p. Can I only use the above five structures during training process? Does this have an impact on model performance?

2. In addition, my graph contains a total of 3300000 triplets, so how do I define the amount of queries in train/valid/test. I noticed that in FB15K237, the amounts are 149689/5000/5000, the number of train queries is close to 1/5 of the total number of triplets. Is this ratio reasonable?

**Comment by bys0318** [comment]
Well, good news! Our method does not require training on specific downstream query structures, meaning you can directly run the inference on 1p, 2p, 3p, 4p, 5p by adding `--tasks 1p,2p,3p,4p,5p` to the command. And, of course, there is no need for splitting train/valid/test.

**Comment by Jasonqte** [comment]
Perfect! Thank you so much for your help!
